name: Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20.x

  #     - name: Check Node Version
  #       run: node -v

  #     - name: Install Dependencies
  #       run: yarn

  #     - name: Install Angular/cli
  #       run: npm i -g @angular/cli@15

  #     - name: Build Angular Application
  #       run: ng build

  # docker:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./docker
  #         push: true
  #         tags: ${{secrets.DOCKER_USERNAME }}/github-workflow:latest

  # testing:
  #   name: test scp action
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4

  #     - name: copy file via ssh password
  #       uses: ./
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USERNAME }}
  #         password: ${{ secrets.SSH_PASSWORD }}
  #         source: "action.yml"
  #         target: "./home/ubuntu"

  build:
    runs-on: ubuntu-latest
    steps:
      # Add a step to list files in the public directory
      - name: List files in the public directory
        run: ls

      - name: Copy files via scp
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: vignesh
          script: |
            echo "Connected to server"
            scp -r ./* ${{ secrets.SERVER_USERNAME }}@${{secrets.SERVER_HOST}}:/home/ubuntu/vignesh
          # Add your commands here
