name: Hello World

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
# jobs:
#   send-telegram-message:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Send Telegram Message
#         uses: appleboy/telegram-action@v0.0.2
#         with:
#           to: ${{ secrets.TELEGRAM_CHAT_ID }}
#           token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#           message: "New commit on branch ${GITHUB_REF}: ${GITHUB_SHA}"
jobs:
  deploy: #Job Name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Check Node Version
        run: node -v

  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        env:
          TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
        run: |
          successMessage="```
            ${{ github.event_name }} event triggered by ${GITHUB_ACTOR}} with ${GITHUB_SHA}}
            Commit Date and Time: ${{ github.event.head_commit.timestamp }}
            Commit Name : ${{ github.event.head_commit.author.name }}
            Commit Author : ${{ github.event.head_commit.author.email }}
            Commit Message : ${{ github.event.head_commit.message }}```
            "
          response=$(curl -s -X POST \
            -d "chat_id=$CHAT_ID" \
            -d "text=$successMessage" \
            https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage)

        # Your deployment steps here
      - name: Build and Deploy
        run: |
          # Commands to build and deploy your application
          # If deployment fails, exit with a non-zero status code
          # For example:
          npm run build || exit 1

      # Check if deployment was successful
      - name: Check Deployment Status
        if: ${{ failure() }}
        run: |
          echo "Deployment failed! Sending notification..."
          # Send notification (e.g., via Telegram, Slack, email, etc.)

      # If deployment was successful, continue with other steps
      - name: Continue with Post-Deployment Steps
        if: ${{ success() }}
        run: |
          echo "Deployment successful! Continuing with post-deployment steps..."
          # Perform any additional post-deployment tasks
