name: Hello World

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
# jobs:
#   send-telegram-message:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Send Telegram Message
#         uses: appleboy/telegram-action@v0.0.2
#         with:
#           to: ${{ secrets.TELEGRAM_CHAT_ID }}
#           token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#           message: "New commit on branch ${GITHUB_REF}: ${GITHUB_SHA}"
jobs:
  deploy: #Job Name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Check Node Version
        run: node -v

  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        env:
          app_id: 1
          TELEGRAM_TOKEN: 6967691600:AAEiHVupwTpWjtT7HovVAI_X8sM4ZWy58ok
        run: |
          successMessage="The APP ID ${app_id} ${{env.TELEGRAM_TOKEN}} Frontend has been successfully deployed on the testing server."
          response=$(curl -s -X POST \
            -d "chat_id=-4135594593" \
            -d "text=$successMessage" \
            https://api.telegram.org/bot${{env.TELEGRAM_TOKEN}}/sendMessage)
          echo "${{env.TELEGRAM_TOKEN}}"
          echo "Telegram API Response: $response"
