name: Telegram Notification

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
# jobs:
#   send-telegram-message:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Send Telegram Message
#         uses: appleboy/telegram-action@v0.0.2
#         with:
#           to: ${{ secrets.TELEGRAM_CHAT_ID }}
#           token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#           message: "New commit on branch ${GITHUB_REF}: ${GITHUB_SHA}"
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        # Specify Node.js version 16
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
